// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBqzpTpMO-MhIzYr5Az-SyxMUHCLETzWUQ',
    appId: '1:826468386637:android:b980b7491d404321e59904',
    messagingSenderId: '826468386637',
    projectId: 'milktrackerproject',
    databaseURL: 'https://milktrackerproject-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'milktrackerproject.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD6_dNWo-wFwk6sRNC-VrM7W-O_2kwj0HE',
    appId: '1:826468386637:ios:5623a3fc64a20a2ae59904',
    messagingSenderId: '826468386637',
    projectId: 'milktrackerproject',
    databaseURL: 'https://milktrackerproject-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'milktrackerproject.appspot.com',
    iosClientId: '826468386637-8222v0g05u31r3j01egqmk216ucvo5fr.apps.googleusercontent.com',
    iosBundleId: 'com.example.untitled1',
  );
}
